In [32]:
import pandas as pd
import numpy as np

In [2]:
df_calories = pd.read_csv('calories_exercise/calories.csv')

In [3]:
df_exercise = pd.read_csv('calories_exercise/exercise.csv')

In [4]:
df_calories.head()

    User_ID  Calories
0  14733363     231.0
1  14861698      66.0
2  11179863      26.0
3  16180408      71.0
4  17771927      35.0

In [5]:
df_exercise.head()

    User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0  14733363    male   68   190.0    94.0      29.0       105.0       40.8
1  14861698  female   20   166.0    60.0      14.0        94.0       40.3
2  11179863    male   69   179.0    79.0       5.0        88.0       38.7
3  16180408  female   34   179.0    71.0      13.0       100.0       40.5
4  17771927  female   27   154.0    58.0      10.0        81.0       39.8

In [6]:
# joining both the datasets
df = pd.merge(df_exercise, df_calories, on='User_ID', how='inner')
df

,User_ID,Gender,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Calories
0,14733363,male,68,190.0,94.0,29.0,105.0,40.8,231.0
1,14861698,female,20,166.0,60.0,14.0,94.0,40.3,66.0
2,11179863,male,69,179.0,79.0,5.0,88.0,38.7,26.0
3,16180408,female,34,179.0,71.0,13.0,100.0,40.5,71.0
4,17771927,female,27,154.0,58.0,10.0,81.0,39.8,35.0
...,...,...,...,...,...,...,...,...,...
14995,15644082,female,20,193.0,86.0,11.0,92.0,40.4,45.0
14996,17212577,female,27,165.0,65.0,6.0,85.0,39.2,23.0
14997,17271188,female,43,159.0,58.0,16.0,90.0,40.1,75.0
14998,18643037,male,78,193.0,97.0,2.0,84.0,38.3,11.0
14999,11751526,male,63,173.0,79.0,18.0,92.0,40.5,98.0

In [19]:
df["Gender"] = df["Gender"].map({'male': 0, "female": 1})

In [20]:
X = df.drop(columns=['User_ID', 'Calories'], axis=1)
y = df['Calories']

In [21]:
from sklearn.model_selection import train_test_split

# Assuming you already have X and y
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [22]:
from sklearn.tree import DecisionTreeRegressor

# Initialize model
dt_reg = DecisionTreeRegressor(random_state=42, max_depth=5)

# Fit model
dt_reg.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=5, random_state=42)

In [25]:
from sklearn import metrics

In [26]:
from sklearn.metrics import mean_squared_error, r2_score

In [27]:
# Predict
y_pred = dt_reg.predict(X_test)

In [28]:
# Metrics
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Decision Tree Regressor Results:")
print("MSE:", mse)
print("R² Score:", r2)

Decision Tree Regressor Results:
MSE: 156.73217610640646
R² Score: 0.9611644513878681

In [30]:
mae = metrics.mean_absolute_error(y_test, y_pred)

In [31]:
print("Mean Absolute Error = ", mae)

Mean Absolute Error =  8.839276203706955